---
language: objective-c

before_script:
  - sudo easy_install cpp-coveralls

script:
  - xctool project DTCoreText.xcodeproj -scheme MacUnitTest test -arch x86_64 ONLY_ACTIVE_ARCH=NO

after_success:
  - ./script/coveralls.sh
